# Unity generated
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/
[Mm]emoryCaptures/
[Rr]ecordings/
[Pp]rofileCaptures/
ProfilerCaptures/

# Visual Studio
.vs/
.vscode/
*.csproj
*.unityproj
*.sln
*.slnx
*.suo
*.user
*.userprefs
*.pidb

# OS
.DS_Store
Thumbs.db

# Crash reports
sysinfo.txt
*.stackdump

# Asset meta — bunları BIRAK (Unity için şart)
# !/Assets/**/*.meta
